import requests

# ollama might not be running so always have fallback
def generate_summary(data):
    verdict = data.get('label', 'UNKNOWN')
    score = data.get('score', 0)
    confidence = data.get('confidence', 0)
    media = data.get('mediaType', 'image')
    fhash = data.get('fileHash', 'N/A')

    prompt = f"""You are a digital forensics expert. Generate a formal forensic analysis report.

Media Type: {media}
Verdict: {verdict}
Manipulation Score: {score}%
Confidence: {confidence}%
SHA-256: {fhash}

Write sections:
1. Executive Summary
2. Technical Findings
3. IT Act 65B Note
4. Recommendation

Be concise and professional."""

    try:
        resp = requests.post('http://localhost:11434/api/generate', json={
            'model': 'llama3.2',
            'prompt': prompt,
            'stream': False
        }, timeout=60)
        return resp.json().get('response', fallback(data))
    except Exception:
        return fallback(data)

def fallback(data):
    verdict = data.get('label', 'UNKNOWN')
    confidence = data.get('confidence', 0)
    media = data.get('mediaType', 'image')
    score = data.get('score', 0)

    return f"""FORENSIC ANALYSIS REPORT

1. Executive Summary
This {media} file has been analyzed using multi-signal forensic techniques. Verdict: {verdict} with {confidence}% confidence.

2. Technical Findings
- Manipulation Score: {score}%
- ELA Score: {data.get('elaScore', 'N/A')}%
- EXIF Status: {data.get('exifLabel', 'N/A')}
- SHA-256: {data.get('fileHash', 'N/A')}

3. IT Act 65B Note
This analysis is generated by an automated forensic system. For legal proceedings, a certified expert must certify findings under Section 65B of the Indian Evidence Act.

4. Recommendation
{'This file shows signs of manipulation and should be treated with caution.' if verdict == 'MANIPULATED' else 'No significant manipulation detected. File appears authentic.'}"""
