import io
import base64
import time
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch


# red for fake green for real
def generate_pdf(data, summary):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=inch,
        rightMargin=inch
    )
    styles = getSampleStyleSheet()
    elems = []

    case_ref = f"FA-{int(time.time())}"
    verdict = data.get('label', 'UNKNOWN')
    verdict_color = colors.HexColor('#ef4444') if verdict == 'MANIPULATED' else colors.HexColor('#22c55e')
    media = data.get('mediaType', 'image')

    # header
    elems.append(Paragraph("FORENSIC ANALYSIS REPORT", styles['Title']))
    elems.append(Paragraph("ForensicAI | CHAK36-CS-05", styles['Normal']))
    elems.append(Spacer(1, 0.1 * inch))
    elems.append(HRFlowable(width='100%', thickness=1, color=colors.grey))
    elems.append(Spacer(1, 0.15 * inch))
    elems.append(Paragraph(f"<b>Case Reference:</b> {case_ref}", styles['Normal']))
    elems.append(Paragraph(f"<b>Generated:</b> {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}", styles['Normal']))
    elems.append(Spacer(1, 0.2 * inch))

    # evidence table
    table_data = [
        ['Field', 'Value'],
        ['Verdict', verdict],
        ['Media Type', str(media).upper()],
        ['Manipulation Score', f"{data.get('score', 0)}%"],
        ['Confidence', f"{data.get('confidence', 0)}%"],
        ['SHA-256 Hash', data.get('fileHash', 'N/A')],
        ['Case Reference', case_ref],
    ]

    if media == 'image':
        table_data.append(['ELA Score', f"{data.get('elaScore', 'N/A')}%"])
        table_data.append(['Model Score', f"{data.get('modelScore', 'N/A')}%"])
        table_data.append(['EXIF Status', data.get('exifLabel', 'N/A')])
        if data.get('exifFlags'):
            table_data.append(['EXIF Flags', ', '.join(data['exifFlags']) or 'none'])
    elif media == 'video':
        table_data.append(['Total Frames', str(data.get('totalFrames', 'N/A'))])
        table_data.append(['Frames Checked', str(data.get('framesChecked', 'N/A'))])
        table_data.append(['Frames Flagged', str(data.get('framesFlagged', 'N/A'))])
    elif media == 'audio':
        table_data.append(['Model Used', data.get('modelUsed', 'N/A')])

    t = Table(table_data, colWidths=[2 * inch, 4.5 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (1, 1), (1, 1), verdict_color),
        ('FONTNAME', (1, 1), (1, 1), 'Helvetica-Bold'),
        ('FONTSIZE', (1, 1), (1, 1), 12),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))

    elems.append(t)
    elems.append(Spacer(1, 0.3 * inch))
    elems.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e2e8f0')))
    elems.append(Spacer(1, 0.15 * inch))

    # summary section
    elems.append(Paragraph("Analysis Summary", styles['Heading2']))
    elems.append(Spacer(1, 0.1 * inch))

    for line in summary.split('\n'):
        line = line.strip()
        if not line:
            elems.append(Spacer(1, 0.05 * inch))
            continue
        # section headers in summary
        if line[0].isdigit() and '.' in line[:3]:
            elems.append(Spacer(1, 0.08 * inch))
            elems.append(Paragraph(f'<b>{line}</b>', styles['Normal']))
        else:
            elems.append(Paragraph(line, styles['Normal']))
        elems.append(Spacer(1, 0.03 * inch))

    elems.append(Spacer(1, 0.3 * inch))
    elems.append(HRFlowable(width='100%', thickness=0.5, color=colors.grey))
    elems.append(Spacer(1, 0.1 * inch))

    footer_style = styles['Normal'].clone('footer')
    footer_style.fontSize = 8
    footer_style.textColor = colors.grey
    elems.append(Paragraph(
        f"Generated by ForensicAI — CHAK36-CS-05 | This report is auto-generated. "
        f"For legal use, certify under IT Act Section 65B. | {case_ref}",
        footer_style
    ))

    doc.build(elems)
    pdf_b64 = base64.b64encode(buf.getvalue()).decode()
    return pdf_b64, case_ref
